### ISSUE TITLE
Spin Command trigger should not terminate host when multiple triggers are defined

### ISSUE THREAD

**Issue by ThorstenHans** [fermyon/spin-trigger-command#21]
I created a Spin App with two triggers:

```toml
# ...

[[trigger.http]]
route = "/..."
component = "api"

[[trigger.command]]
component = "cleanup"

# ...
```

## Actual Behavior

Upon starting the app with `spin up`, the `cleanup` component is invoked. Once the component finished processing, the `spin up` process is terminated.

## Expected Behavior

The `spin up` host process should stay alive once the `cleanup` component  has finished processing
